[core]
socket_path = "./build/spear.sock"
plugin_dir = "./build/plugins"
log_level = "debug"
pid_file = "./build/spear.pid"

[plugins]
authwatch = { enabled = true }
smtp = { enabled = true }

# SMTP Email Trigger Configuration
# Complete example showing all available options

[[trigger]]
id = "email_alert"
plugin = "smtp"
action = "send_email"

# Required fields
host = "smtp.gmail.com"                        # SMTP server hostname
from = "teto.kasane@gmail.com"                 # From email address
to = ["miku@vocaloid.com", "neru@fanloid.com"] # Recipient addresses

# Optional authentication (leave empty for no auth)
username = "teto.kasane@gmail.com"             # SMTP username
password = "your-app-password"                 # SMTP password

# Optional recipient lists
cc = ["rin@vocaloid.com"]                      # Carbon copy recipients
bcc = ["len@vocaloid.com"]                     # Blind carbon copy recipients

# Connection settings (with defaults)
port = 587                                    # SMTP port (default: 587)
use_starttls = true                           # Use STARTTLS (default: true)
use_tls = false                               # Use direct TLS (default: false)
timeout = 30                                  # Connection timeout in seconds (default: 30)

# Retry settings (with defaults)
max_retries = 3                               # Maximum retry attempts (default: 3)
retry_delay = 5                               # Delay between retries in seconds (default: 5)

# Email content templates using Go template syntax
subject = "Spear Alert - {{.Args.alert_type}}"  # Subject template
template = """Security Alert: {{.Args.alert_type}}

Timestamp: {{.Timestamp}}
Trigger ID: {{.TriggerID}}

Event Details:
{{range $key, $value := .Args}}  • {{$key}}: {{$value}}
{{end}}
---
This alert was generated by Spear Security Monitor."""  # Body template with Go template syntax

# Common SMTP configurations:

# Gmail
[[trigger]]
id = "gmail_example"
plugin = "smtp"
action = "send_email"
host = "smtp.gmail.com"
port = 587
username = "luka@vocaloid.com"
password = "your-app-password"
from = "luka@vocaloid.com"
to = ["kaito@vocaloid.com"]
use_starttls = true

# Office365
[[trigger]]
id = "office365_example"
plugin = "smtp"
action = "send_email"
host = "smtp.office365.com"
port = 587
username = "meiko@crypton.onmicrosoft.com"
password = "office365-password"
from = "meiko@crypton.onmicrosoft.com"
to = ["gumi@internet.com"]
use_starttls = true

# Local SMTP without authentication
[[trigger]]
id = "local_example"
plugin = "smtp"
action = "send_email"
host = "localhost"
port = 25
from = "ia@localhost"
to = ["une@localhost"]
use_starttls = false

# TLS connection (port 465)
[[trigger]]
id = "tls_example"
plugin = "smtp"
action = "send_email"
host = "secure-mail.example.com"
port = 465
username = "yukari@voiceroid.com"
password = "secure-password"
from = "yukari@voiceroid.com"
to = ["akane@voiceroid.com"]
use_tls = true
use_starttls = false

# Use email trigger with authwatch
[[authwatch]]
id = "ssh_monitor"
services = ["ssh"]
triggers = ["email_alert"]
time_window = 300
max_hits = 5